=head1 NAME

Data::Range::Compare::Cookbook --  Tutorials and Recipes

=head1 SYNOPSIS

  perldoc Data::Range::Compare::Cookbook

=head1 RECIPES

=over 3

=item L<Data::Range::Compare::Cookbook::Recipe_a_to_z> - the "a to z" example

This recipe is a basic tutorial on how to use the Data::Range::Compare framework to manipulate ranges, using a .. z as the range example.

=item L<Data::Range::Compare::Cookbook::Recipe_subclass_a_to_z> - subclassing "a to z"

This recipe builds on Data::Range::Compare::Cookbook::Recipe_a_to_z and demonstrates how to subclass Data::Range::Compare in a new module and provides a demo script explaining how to use the new module.

=back

=head1 AUTHOR

Michael Shipper

=head1 COPYRIGHT

Copyright 2010 Michael Shipper.  All rights reserved.

This library is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=head1 SEE ALSO

perldoc(1).

=cut

